stages:
    - build
    - test

cache:
    key: "$CI_BUILD_STAGE/$CI_BUILD_REF_NAME"
		paths:
		    - node_modules

build:6.9:
    image: node:6.9
    stage: build
    script:
        - npm install
        - npm run build

test:6.9:
    image: node:6.9
    stage: test
    script:
        - npm test

build:7.4:
    image: node:7.4
    stage: build
    script:
        - npm install
        - npm run build

test:7.4:
    image: node:7.4
    stage: test
    script:
        - npm test