stages:
    - build
    - test

cache:
    paths:
        - node_modules

before_script:
    - apt-get install yarn
    - yarn install

build:6.9:
    image: node:6.9
    stage: build
    script:
        - yarn run build

test:6.9:
    image: node:6.9
    stage: test
    script:
        - yarn test

build:7.4:
    image: node:7.4
    stage: build
    script:
        - yarn run build

test:7.4:
    image: node:7.4
    stage: test
    script:
        - yarn test